baseURL = "https://nx10.github.io/"
languageCode = "en-us"
title = "Florian Rupprecht"
theme = "anatole"


# Enable Disqus
#disqusShortname = ""

# Google Analytics
googleAnalytics = "UA-189107729-1"

# Syntax highlighting
pygmentsUseClasses = true 
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true


[params]
title = "Florian Rupprecht"
author = "Florian Rupprecht"
#copyright = "2020-2021"
description = "Researcher in Cognitive Neuroscience"
profilePicture = "images/profile.jpg"
keywords = ""
favicon = "favicons/"
# example ["css/custom.css"]
customCss = ["css/custom.css"]
# example ["js/custom.js"]
customJs = [] 
mainSections = ["news"]
images = ["images/site-feature-image.png"]
doNotLoadAnimations = true
# Form Spree Contact Form
#contactFormAction = "https://formspree.io/f/your-form-hash-here"
# Google Site Verify
#googleSiteVerify = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
# indexDateFormat = "Mon, Jan 2, 2006"
# listDateFormat = "Jan 2"
# singleDateFormat = "Mon, Jan 2, 2006"

[params.simpleAnalytics]
# enable = true
# customurl = "https://analytics.example.com"

## Math settings
[params.math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links
# use 'fab' when brand icons, use 'fas' when standard solid icons.
[[params.socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/nx10/"

[[params.socialIcons]]
icon = "fab fa-researchgate"
title = "Reseach Gate"
url = "https://www.researchgate.net/profile/Florian_Rupprecht2"

[[params.socialIcons]]
icon = "fab fa-orcid"
title = "ORCID"
url = "https://orcid.org/0000-0002-1795-8624"

[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:floruppr@gmail.com"

## Menu items

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"
  
  [[menu.main]]
  name = "News"
  identifier = "news"
  weight = 100
  url = "/news/"

  [[menu.main]]
  name = "Publications"
  weight = 200
  identifier = "pubs"
  url = "/pubs/"
  
